"""Init migration

Revision ID: 5868057f4869
Revises: 
Create Date: 2025-05-08 15:32:46.380873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5868057f4869'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('API_CLIENT', 'ANONYMOUS_CLIENT', 'ADMIN', 'MANAGER', name='usercategory').create(op.get_bind())
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('sign', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('category', postgresql.ENUM('API_CLIENT', 'ANONYMOUS_CLIENT', 'ADMIN', 'MANAGER', name='usercategory', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_crncy_id', sa.Integer(), nullable=False),
    sa.Column('target_crncy_id', sa.Integer(), nullable=False),
    sa.Column('_value', sa.Float(precision=6), nullable=False),
    sa.ForeignKeyConstraint(['base_crncy_id'], ['currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_crncy_id'], ['currency.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_crncy_id', 'target_crncy_id')
    )
    op.create_table('token_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('refresh', 'access', native_enum=False), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_state')
    op.drop_table('exchange_rate')
    op.drop_table('user')
    op.drop_table('currency')
    sa.Enum('API_CLIENT', 'ANONYMOUS_CLIENT', 'ADMIN', 'MANAGER', name='usercategory').drop(op.get_bind())
    # ### end Alembic commands ###
