services:
  db:
    image: postgres:16-alpine
    volumes:
      - currency_exch_fapi_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    healthcheck:
      test: nc -z $$DB_HOST $$DB_PORT || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    ports:
      - "5435:5432"

volumes:
  currency_exch_fapi_postgres_data: