services:
  currency_exchange_service:
    ports: !reset []
    expose:
      - '8000'

  currency_exchange_proxy:
    build:
      context: ./nginx
      dockerfile_inline: |
        FROM nginx:latest
        RUN rm /etc/nginx/conf.d/default.conf
        COPY nginx.conf /etc/nginx/conf.d

    ports:
      - '${NGINX_LISTEN_PORT:-80}:80'
    depends_on:
      - currency_exchange_service



